language: php

cache: vendor

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

env:
  - SYMFONY_VERSION=2.6.*

matrix:
  include:
    - php: 5.3.3
      env: SYMFONY_VERSION=2.3.* COMPOSER_FLAGS="--prefer-lowest"
    - php: 5.6
      env: SYMFONY_VERSION=2.3.*
    - php: 5.6
      env: SYMFONY_VERSION=2.5.*
    - php: 5.6
      env: SYMFONY_VERSION=2.7.*@dev
  allow_failures:
    - php: hhvm
    - env: SYMFONY_VERSION=2.7.*@dev
    - php: nightly


services:
  - memcached
  - mongodb
  - redis-server

before_script:
  - echo "extension=mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension=memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension=apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - wget https://getcomposer.org/composer.phar
  - php composer.phar install --dev --prefer-source
  # must be set after composer to avoid issue with autoloading
  - echo "apc.enable_cli=On" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo pip install -r Resources/doc/requirements.txt

script: make test

notifications:
    webhooks: https://sonata-project.org/bundles/cache/master/travis
